### ISSUE TITLE
Unknown power source for QBKG03LM and QBKG04LM

### ISSUE THREAD

**Issue by slydiman** [danielwelch/hassio-zigbee2mqtt#436] opened 2020-10-04 10:47 UTC
Zigbee2mqtt v1.15.0 add-on shows unknown power source for devices QBKG03LM and QBKG04LM. 
Reconfiguration does not help.
![invalid_power](https://user-images.githubusercontent.com/16115622/95013273-52215a80-0650-11eb-8912-c98a2690be32.jpg)

**Comment by V-Zemlyakov** [comment] 2020-10-05 07:07
![изображение](https://user-images.githubusercontent.com/7317817/95049398-5a31d680-06f2-11eb-86f0-902f01f004e1.png)
and LLKZMK11LM

**Comment by ciotlosm** [comment] 2020-10-05 07:34
There are probably more, but this is not a problem with the add-on. I think it's just a rendering problem with the built-in frontend, where it gets its data. I will leave this item opened for now, but the icon should not cause any issues with your setup.

**Comment by slydiman** [comment] 2020-10-05 10:21
In the SLS gateway with the same UI such icon usually means an incomplete device interview after peering.
I'm sure it is not too hard to fix this issue. Thanks.

**Comment by ciotlosm** [comment] 2020-10-10 06:21
The code that calculates that icon is here: 
https://github.com/nurikk/z2m-frontend/blob/6a89c9eca1b399cea40859d64c17dff8d0c23042/src/components/power-source/index.tsx#L12

The available types are here:
https://github.com/Koenkk/zigbee-herdsman/blob/e55f57311efc167c23394edd7263fcfc89c05830/src/zcl/definition/powerSource.ts#L1

The type of power source seems to have some sort of automatic detection:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/8466c085ce85e4dc355e420e09c1530b6a7d3b8a/index.js#L101

I believe that in the case of the devices above the problem is that they are connected to mains, but don't have neutral wire, so can't function as routers. They are considered end devices, but don't have battery power. 

The problem that I have also is with LLKZMK11LM which are routers as well and connected to main power and also have neutral wire. 

I have raised https://github.com/nurikk/z2m-frontend/issues/43 with the frontend repo, but at the moment I can't figure out which messages are wrong for the devices.

**Comment by ciotlosm** [comment] 2020-10-10 07:12
This should be fixed in Edge, according to https://github.com/nurikk/z2m-frontend/commit/d79829379c0c35ec01340dc5613e7d8c7788efdc#diff-1a4a20802399da556e0eb82075224ce8

**Closed** 2020-10-10 09:30 UTC
Labels: bug
