### ISSUE TITLE
homeassistant_legacy_triggers is not working

### ISSUE THREAD

**Issue by andriej** [danielwelch/hassio-zigbee2mqtt#375] opened 2020-09-03 09:18 UTC
**zigbee2mqtt add-on version (if edge, please report commit hash):** 0.14.4

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):** Debian 10 Supervised

**Description of problem:**
Options regarding HA legacy mode doesn't work in configuration:
`homeassistant_legacy_triggers: false` is marked as unknown option in logs...

**Your entire configuration from the frontend (with sensitive fields redacted)**:
n/a

**Your logs from Hass.io**
n/a

**Comment by apeeters** [comment] 2020-09-03 11:51
This is a duplicate of #313.

**Comment by lovelylain** [comment] 2020-09-04 02:12
I added support for almost all options #353

**Closed** 2020-09-09 20:29 UTC
