### ISSUE TITLE
can't install addon on rpi3b ubuntu 18.04.2 armhf

### ISSUE THREAD

**Issue by hatemfares** [danielwelch/hassio-zigbee2mqtt#125] opened 2019-03-09 19:31 UTC
19-03-09 18:53:37 INFO (SyncWorker_5) [hassio.docker.interface] Pull image dwelch2101/zigbee2mqtt-armv7 tag 1.1.1.
19-03-09 18:53:38 ERROR (SyncWorker_5) [hassio.docker.interface] Can't install dwelch2101/zigbee2mqtt-armv7:1.1.1 -> 404 Client Error: Not Found ("pull access denied for dwelch2101/zigbee2mqtt-armv7, repository does not exist or may require 'docker login'").

**Comment by liads** [comment] 2019-03-09 22:33
I've just hit it too on rpi2.
Seems like a recent update in hassio changed the architecture for rpi from armhf to armv7, which is not built for the zigbee2mqtt addon.

**Comment by liads** [comment] 2019-03-09 23:31
See #123

**Comment by danielwelch** [comment] 2019-03-10 02:51
Duplicate of #124

**Closed by danielwelch** 2019-03-10 02:51 UTC

**Comment by danielwelch** [comment] 2019-03-10 02:53
Duplicate of #123
