### ISSUE TITLE
Edge won't update (1.13.1-dev)

### ISSUE THREAD

**Issue by KoenHaemels** [danielwelch/hassio-zigbee2mqtt#368] opened 2020-08-11 21:11 UTC
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.13.1-dev (commit #)

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**
Docker Hass.io

**Description of problem:**
Edge won't update even with auto-update turned on. I have to remove and re-add zigbee2mqtt but with the problem that i loose my whole setup.

**Your logs from Hass.io**

```
}Debug information end
./run.sh: line 24: [Info] Configuration backup found in /share/dev/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2020-08-11T23:01:08: PM2 log: Launching in no daemon mode
2020-08-11T23:01:08: PM2 log: App [npm:0] starting in -fork mode-
2020-08-11T23:01:08: PM2 log: App [npm:0] online
> zigbee2mqtt@1.13.1-dev start /app
> node index.js
zigbee2mqtt:info  2020-08-11 23:01:09: Logging to console and directory: '/share/dev/zigbee2mqtt/log/2020-08-11.23-01-09' filename: log.txt
zigbee2mqtt:info  2020-08-11 23:01:10: Starting zigbee2mqtt version 1.13.1-dev (commit #)
```

**Comment by theFork** [comment] 2020-09-16 10:56
I can confirm that this behaviour is still present with 1.14.4-dev. Unfortunately, there in no commit hash given in the startup log. Is the edge version (aka the dev branch) aware of the latest commit hash?

**Comment by ciotlosm** [comment] 2020-09-17 12:29
The missing commit id for edge is a known problem https://github.com/danielwelch/hassio-zigbee2mqtt/issues/146

**Comment by danielwelch** [comment] 2020-09-17 13:24
Thanks @ciotlosm. The problems are in this part of the dockerfile: https://github.com/danielwelch/hassio-zigbee2mqtt/blob/727077936583dd7c05b9a8bc4e00eabf832d35ad/zigbee2mqtt-edge/Dockerfile#L25

First, this approach is giving us the commit for the add-on, not zigbee2mqtt. Second, I think the usage of environment variables in `jq` isn't correct and is outputting `null`.

I think this could be easily fixed for edge by changing the above to something like: `RUN jq -n --arg commit $(eval git rev-parse --short HEAD) '{"hash": $commit }' > ./.hash.json`. I can push this change for edge. Won't be able to do this for stable (non-edge) because we don't `git clone` during image build, but download a release instead.

As for the original issue in this thread, this is known expected behavior that is documented in the README:
>To update the edge version of the add-on, you will need to uninstall and re-install the add-on. If you have reinstalled the add-on and believe that the latest version has not been installed, try removing the repository before reinstalling.

The reason for this is tied up in how Home Assistant manages add-on versioning.

**Comment by theFork** [comment] 2020-09-17 17:19
> I can push this change for edge. Won't be able to do this for stable (non-edge) because we don't git clone during image build, but download a release instead.

This would be great! IMHO for the stable version it's not that important to get the exact commit id in the log since here we only have well-known tagged versions.

**Comment by ciotlosm** [comment] 2020-09-18 08:32
Closing this issue as the `edge` process currently requires reinstall, and the commit issue should be fixed with https://github.com/danielwelch/hassio-zigbee2mqtt/pull/388

**Closed by ciotlosm** 2020-09-18 08:32 UTC
