### ISSUE TITLE
Issues with OTA running on Edge

### ISSUE THREAD

**Issue by a8ree** [danielwelch/hassio-zigbee2mqtt#524] opened 2021-01-28 17:50 UTC
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.17.0-dev commit: 435963a
**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**
HassOS / Raspberry PI 4

I've got a couple of installations of Zigbee2mqtt. One is using the docker lastest-dev and the other is using HassOS edge.

I'm trying to update some Ikea sockets using the OTA updates. On the docker image, I followed the instructions, added in the ikea_ota_use_test_url: true and started updating without issue

On the HassIO edge install, I did the same however it gave me an issue - "Image is truncated: not long enough to contain a valid tag"
I've noticed that despite having ikea_ota_use_test_url: true in the config, this line is ignored on startup
The web interface states 1.17.0-dev commit: 435963a
Does this release not have the OTA for Ikea?

```json
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: mqtt
  password: mqtt
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: info
  pan_id: 6755
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  ikea_ota_use_test_url: true
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Your logs from Home Assistant**
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Debug information
-----
-----
{
  "data_path": "/share/zigbee2mqtt",
  "external_converters": [],
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://core-mosquitto",
    "user": "mqtt",
    "password": "mqtt"
  },
  "serial": {
    "port": "/dev/ttyUSB0"
  },
  "advanced": {
    "log_level": "info",
    "pan_id": 6755,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blocklist": [],
    "availability_passlist": []
  },
  "device_options": {},
  "blocklist": [],
  "passlist": [],
  "queue": {},
  "frontend": {
    "port": 8099
  },
  "experimental": {
    "new_api": true
  },
  "socat": {
    "enabled": false,
    "master": "pty,raw,echo=0,link=/dev/ttyZ2M,mode=777",
    "slave": "tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5",
    "restartdelay": 1.0,
    "initialdelay": 1.0,
    "options": "-d -d",
    "log": false
  }
}Debug information end
./run.sh: line 24: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory

**Comment by a8ree** [comment] 2021-01-28 21:46
I've just determined that the configuration is reset on each service restart....why?

**Comment by dreimer1986** [comment] 2021-01-29 09:48
https://github.com/danielwelch/hassio-zigbee2mqtt/issues/493

**Comment by ciotlosm** [comment] 2021-02-11 14:24
ikea_ota_use_test_url was not available in that version. It was just added to `edge` version for https://github.com/zigbee2mqtt/hassio-zigbee2mqtt

**Comment by ciotlosm** [comment] 2021-02-11 14:24
Closing as duplicate of #493

**Closed as completed by ciotlosm** 2021-02-11 14:24 UTC
