### ISSUE TITLE
"Missing availability_blocklist in advanced" 

### ISSUE THREAD

**Issue by Arnchi** [danielwelch/hassio-zigbee2mqtt#391] opened 2020-09-18 04:44 UTC
zigbe to mqqt addon 1.14.4.1 , Hass.io ,rasppi 3 , cc2531

Overnight error while not changing anyhting about  missing availabilty_blocklist in advanced.
Is this a new name for Black list tried to swap them but didnt solve the issues any ideas what could have gone wrong ? 
Good lesson for me to turn off auto updates and only do them when i have time to check them aswell :P
my configuration is : 

data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: mqtt_user
  password: mqtt_user
serial:
  disable_led: true
  port: /dev/ttyACM0
advanced:
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blacklist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
ban: []
whitelist: []

**Comment by Arnchi** [comment] 2020-09-18 05:07
Also I managed to upload my configuration in zigbeetomqqt edge and that works so I am back up and running but preferable switch back to nomral zigbeetomqqt.
 But nevertheless I am and running so thats good !!

**Comment by StephanU** [comment] 2020-09-18 05:13
I think this is a duplicate to #384 
What solved this problem for me was the answer by @tomekpur https://github.com/danielwelch/hassio-zigbee2mqtt/issues/384#issuecomment-693650970

**Comment by ciotlosm** [comment] 2020-09-18 07:10
Indeed, this is a duplicate of https://github.com/danielwelch/hassio-zigbee2mqtt/issues/384

**Closed by ciotlosm** 2020-09-18 07:10 UTC

**Comment by Arnchi** [comment] 2020-09-18 07:17
I will check tonight sorry for making double comment.
Thank you for the quick responses though 👍🏻

**Comment by iBobik** [comment] 2020-09-23 21:02
Yeah, it was really good move to solve racism in USA by breaking our home automations with auto updates on. ;-)
