### ISSUE TITLE
All devices connected to MQTT do not update their status

### ISSUE THREAD

**Issue by zhaotianhao1234** [danielwelch/hassio-zigbee2mqtt#358] opened 2020-07-19 22:30 UTC
zigbee2mqtt-edge
```
    "server": "mqtt://core-mosquitto",
    "user": "mqtt",
    "password": "mqtt"
  },
  "serial": {
    "port": "tcp://192.168.1.20:8880"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {},
  "experimental": {},
  "socat": {
    "enabled": false,
    "master": "pty,raw,echo=0,link=/dev/ttyZ2M,mode=777",
    "slave": "tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5",
    "restartdelay": 1.0,
    "initialdelay": 1.0,
    "options": "-d -d",
    "log": false
  }
}
```
Debug information end
```
./run.sh: line 24: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2020-07-20T06:22:07: PM2 log: Launching in no daemon mode
2020-07-20T06:22:07: PM2 log: App [npm:0] starting in -fork mode-
2020-07-20T06:22:07: PM2 log: App [npm:0] online
> zigbee2mqtt@1.14.1-dev start /app
> node index.js
zigbee2mqtt:info  2020-07-20 06:22:11: Logging to console and directory: '/share/zigbee2mqtt/log/2020-07-20.06-22-11' filename: log.txt
zigbee2mqtt:info  2020-07-20 06:22:11: Starting zigbee2mqtt version 1.14.1-dev (commit #)
zigbee2mqtt:info  2020-07-20 06:22:11: Starting zigbee-herdsman...
zigbee2mqtt:info  2020-07-20 06:22:14: zigbee-herdsman started
zigbee2mqtt:info  2020-07-20 06:22:14: Coordinator firmware version: '{"type":"zStack30x","meta":{"transportrev":2,"product":2,"majorrel":2,"minorrel":7,"maintrel":2,"revision":20200327}}'
zigbee2mqtt:info  2020-07-20 06:22:14: Currently 4 devices are joined:
zigbee2mqtt:info  2020-07-20 06:22:14: 0x04cf8cdf3c775734 (0x04cf8cdf3c775734): GZCGQ01LM - Xiaomi MiJia light intensity sensor (EndDevice)
zigbee2mqtt:info  2020-07-20 06:22:14: 0x04cf8cdf3c77185d (0x04cf8cdf3c77185d): GZCGQ01LM - Xiaomi MiJia light intensity sensor (EndDevice)
zigbee2mqtt:info  2020-07-20 06:22:14: 0x04cf8cdf3c7718d4 (0x04cf8cdf3c7718d4): GZCGQ01LM - Xiaomi MiJia light intensity sensor (EndDevice)
zigbee2mqtt:info  2020-07-20 06:22:14: 0x00158d00044f95a2 (0x00158d00044f95a2): RTCGQ01LM - Xiaomi MiJia human body movement sensor (EndDevice)
zigbee2mqtt:info  2020-07-20 06:22:14: Zigbee: disabling joining new devices.
zigbee2mqtt:info  2020-07-20 06:22:14: Configuring '0x04cf8cdf3c775734'
zigbee2mqtt:info  2020-07-20 06:22:14: Connecting to MQTT server at mqtt://core-mosquitto
zigbee2mqtt:info  2020-07-20 06:22:15: Connected to MQTT server
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c775734', payload '{"battery":100,"voltage":3100,"linkquality":73,"illuminance":22765,"illuminance_lux":188}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c77185d', payload '{"battery":100,"voltage":3100,"linkquality":94,"illuminance":21106,"illuminance_lux":128}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c7718d4', payload '{"battery":100,"voltage":3100,"linkquality":68,"illuminance":38257,"illuminance_lux":6693}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'zigbee2mqtt/0x00158d00044f95a2', payload '{"occupancy":false,"linkquality":63,"battery":100,"voltage":3065}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.14.1-dev","commit":"","coordinator":{"type":"zStack30x","meta":{"transportrev":2,"product":2,"majorrel":2,"minorrel":7,"maintrel":2,"revision":20200327}},"log_level":"info","permit_join":false}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'homeassistant/sensor/0x04cf8cdf3c775734/battery/config', payload '{"unit_of_measurement":"%","device_class":"battery","value_template":"{{ value_json.battery }}","state_topic":"zigbee2mqtt/0x04cf8cdf3c775734","json_attributes_topic":"zigbee2mqtt/0x04cf8cdf3c775734","name":"0x04cf8cdf3c775734_battery","unique_id":"0x04cf8cdf3c775734_battery_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x04cf8cdf3c775734"],"name":"0x04cf8cdf3c775734","sw_version":"Zigbee2mqtt 1.14.1-dev","model":"MiJia light intensity sensor (GZCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'homeassistant/sensor/0x04cf8cdf3c775734/illuminance/config', payload '{"unit_of_measurement":"-","device_class":"illuminance","value_template":"{{ value_json.illuminance }}","state_topic":"zigbee2mqtt/0x04cf8cdf3c775734","json_attributes_topic":"zigbee2mqtt/0x04cf8cdf3c775734","name":"0x04cf8cdf3c775734_illuminance","unique_id":"0x04cf8cdf3c775734_illuminance_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x04cf8cdf3c775734"],"name":"0x04cf8cdf3c775734","sw_version":"Zigbee2mqtt 1.14.1-dev","model":"MiJia light intensity sensor (GZCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'homeassistant/sensor/0x04cf8cdf3c775734/illuminance_lux/config', payload '{"unit_of_measurement":"lx","device_class":"illuminance","value_template":"{{ value_json.illuminance_lux }}","state_topic":"zigbee2mqtt/0x04cf8cdf3c775734","json_attributes_topic":"zigbee2mqtt/0x04cf8cdf3c775734","name":"0x04cf8cdf3c775734_illuminance_lux","unique_id":"0x04cf8cdf3c775734_illuminance_lux_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x04cf8cdf3c775734"],"name":"0x04cf8cdf3c775734","sw_version":"Zigbee2mqtt 1.14.1-dev","model":"MiJia light intensity sensor (GZCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'homeassistant/sensor/0x04cf8cdf3c775734/linkquality/config', payload '{"icon":"mdi:signal","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0x04cf8cdf3c775734","json_attributes_topic":"zigbee2mqtt/0x04cf8cdf3c775734","name":"0x04cf8cdf3c775734_linkquality","unique_id":"0x04cf8cdf3c775734_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x04cf8cdf3c775734"],"name":"0x04cf8cdf3c775734","sw_version":"Zigbee2mqtt 1.14.1-dev","model":"MiJia light intensity sensor (GZCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'homeassistant/sensor/0x04cf8cdf3c77185d/battery/config', payload '{"unit_of_measurement":"%","device_class":"battery","value_template":"{{ value_json.battery }}","state_topic":"zigbee2mqtt/0x04cf8cdf3c77185d","json_attributes_topic":"zigbee2mqtt/0x04cf8cdf3c77185d","name":"0x04cf8cdf3c77185d_battery","unique_id":"0x04cf8cdf3c77185d_battery_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x04cf8cdf3c77185d"],"name":"0x04cf8cdf3c77185d","sw_version":"Zigbee2mqtt 1.14.1-dev","model":"MiJia light intensity sensor (GZCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'homeassistant/sensor/0x04cf8cdf3c77185d/illuminance/config', payload '{"unit_of_measurement":"-","device_class":"illuminance","value_template":"{{ value_json.illuminance }}","state_topic":"zigbee2mqtt/0x04cf8cdf3c77185d","json_attributes_topic":"zigbee2mqtt/0x04cf8cdf3c77185d","name":"0x04cf8cdf3c77185d_illuminance","unique_id":"0x04cf8cdf3c77185d_illuminance_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x04cf8cdf3c77185d"],"name":"0x04cf8cdf3c77185d","sw_version":"Zigbee2mqtt 1.14.1-dev","model":"MiJia light intensity sensor (GZCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'homeassistant/sensor/0x04cf8cdf3c77185d/illuminance_lux/config', payload '{"unit_of_measurement":"lx","device_class":"illuminance","value_template":"{{ value_json.illuminance_lux }}","state_topic":"zigbee2mqtt/0x04cf8cdf3c77185d","json_attributes_topic":"zigbee2mqtt/0x04cf8cdf3c77185d","name":"0x04cf8cdf3c77185d_illuminance_lux","unique_id":"0x04cf8cdf3c77185d_illuminance_lux_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x04cf8cdf3c77185d"],"name":"0x04cf8cdf3c77185d","sw_version":"Zigbee2mqtt 1.14.1-dev","model":"MiJia light intensity sensor (GZCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'homeassistant/sensor/0x04cf8cdf3c77185d/linkquality/config', payload '{"icon":"mdi:signal","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0x04cf8cdf3c77185d","json_attributes_topic":"zigbee2mqtt/0x04cf8cdf3c77185d","name":"0x04cf8cdf3c77185d_linkquality","unique_id":"0x04cf8cdf3c77185d_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x04cf8cdf3c77185d"],"name":"0x04cf8cdf3c77185d","sw_version":"Zigbee2mqtt 1.14.1-dev","model":"MiJia light intensity sensor (GZCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'homeassistant/sensor/0x04cf8cdf3c7718d4/battery/config', payload '{"unit_of_measurement":"%","device_class":"battery","value_template":"{{ value_json.battery }}","state_topic":"zigbee2mqtt/0x04cf8cdf3c7718d4","json_attributes_topic":"zigbee2mqtt/0x04cf8cdf3c7718d4","name":"0x04cf8cdf3c7718d4_battery","unique_id":"0x04cf8cdf3c7718d4_battery_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x04cf8cdf3c7718d4"],"name":"0x04cf8cdf3c7718d4","sw_version":"Zigbee2mqtt 1.14.1-dev","model":"MiJia light intensity sensor (GZCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'homeassistant/sensor/0x04cf8cdf3c7718d4/illuminance/config', payload '{"unit_of_measurement":"-","device_class":"illuminance","value_template":"{{ value_json.illuminance }}","state_topic":"zigbee2mqtt/0x04cf8cdf3c7718d4","json_attributes_topic":"zigbee2mqtt/0x04cf8cdf3c7718d4","name":"0x04cf8cdf3c7718d4_illuminance","unique_id":"0x04cf8cdf3c7718d4_illuminance_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x04cf8cdf3c7718d4"],"name":"0x04cf8cdf3c7718d4","sw_version":"Zigbee2mqtt 1.14.1-dev","model":"MiJia light intensity sensor (GZCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'homeassistant/sensor/0x04cf8cdf3c7718d4/illuminance_lux/config', payload '{"unit_of_measurement":"lx","device_class":"illuminance","value_template":"{{ value_json.illuminance_lux }}","state_topic":"zigbee2mqtt/0x04cf8cdf3c7718d4","json_attributes_topic":"zigbee2mqtt/0x04cf8cdf3c7718d4","name":"0x04cf8cdf3c7718d4_illuminance_lux","unique_id":"0x04cf8cdf3c7718d4_illuminance_lux_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x04cf8cdf3c7718d4"],"name":"0x04cf8cdf3c7718d4","sw_version":"Zigbee2mqtt 1.14.1-dev","model":"MiJia light intensity sensor (GZCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'homeassistant/sensor/0x04cf8cdf3c7718d4/linkquality/config', payload '{"icon":"mdi:signal","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0x04cf8cdf3c7718d4","json_attributes_topic":"zigbee2mqtt/0x04cf8cdf3c7718d4","name":"0x04cf8cdf3c7718d4_linkquality","unique_id":"0x04cf8cdf3c7718d4_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x04cf8cdf3c7718d4"],"name":"0x04cf8cdf3c7718d4","sw_version":"Zigbee2mqtt 1.14.1-dev","model":"MiJia light intensity sensor (GZCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'homeassistant/binary_sensor/0x00158d00044f95a2/occupancy/config', payload '{"payload_on":true,"payload_off":false,"value_template":"{{ value_json.occupancy }}","device_class":"motion","state_topic":"zigbee2mqtt/0x00158d00044f95a2","json_attributes_topic":"zigbee2mqtt/0x00158d00044f95a2","name":"0x00158d00044f95a2_occupancy","unique_id":"0x00158d00044f95a2_occupancy_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d00044f95a2"],"name":"0x00158d00044f95a2","sw_version":"Zigbee2mqtt 1.14.1-dev","model":"MiJia human body movement sensor (RTCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'homeassistant/sensor/0x00158d00044f95a2/battery/config', payload '{"unit_of_measurement":"%","device_class":"battery","value_template":"{{ value_json.battery }}","state_topic":"zigbee2mqtt/0x00158d00044f95a2","json_attributes_topic":"zigbee2mqtt/0x00158d00044f95a2","name":"0x00158d00044f95a2_battery","unique_id":"0x00158d00044f95a2_battery_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d00044f95a2"],"name":"0x00158d00044f95a2","sw_version":"Zigbee2mqtt 1.14.1-dev","model":"MiJia human body movement sensor (RTCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:info  2020-07-20 06:22:15: MQTT publish: topic 'homeassistant/sensor/0x00158d00044f95a2/linkquality/config', payload '{"icon":"mdi:signal","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0x00158d00044f95a2","json_attributes_topic":"zigbee2mqtt/0x00158d00044f95a2","name":"0x00158d00044f95a2_linkquality","unique_id":"0x00158d00044f95a2_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d00044f95a2"],"name":"0x00158d00044f95a2","sw_version":"Zigbee2mqtt 1.14.1-dev","model":"MiJia human body movement sensor (RTCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
zigbee2mqtt:error 2020-07-20 06:22:24: Failed to configure '0x04cf8cdf3c775734', attempt 1 (Error: Bind 0x04cf8cdf3c775734/1 genPowerCfg from '0x00124b0006104d8c/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7))
zigbee2mqtt:info  2020-07-20 06:22:24: Configuring '0x04cf8cdf3c77185d'
zigbee2mqtt:error 2020-07-20 06:22:34: Failed to configure '0x04cf8cdf3c77185d', attempt 1 (Error: Bind 0x04cf8cdf3c77185d/1 genPowerCfg from '0x00124b0006104d8c/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7))
zigbee2mqtt:info  2020-07-20 06:22:34: Configuring '0x04cf8cdf3c7718d4'
zigbee2mqtt:error 2020-07-20 06:22:44: Failed to configure '0x04cf8cdf3c7718d4', attempt 1 (Error: Bind 0x04cf8cdf3c7718d4/1 genPowerCfg from '0x00124b0006104d8c/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7))
```

**Comment by dgreebe** [comment] 2020-07-23 05:58
You are missing in the advance settings the option, report: true

**Comment by ciotlosm** [comment] 2020-09-17 08:25
Does this work with stable version? 
@zhaotianhao1234 is the above issue with valid?

**Comment by ciotlosm** [comment] 2020-09-18 08:04
Closing this as the issue is related to https://github.com/Koenkk/zigbee2mqtt

**Closed by ciotlosm** 2020-09-18 08:04 UTC
